(custom-set-variables
  ;; custom-set-variables was added by Custom -- don't edit or cut/paste it!
  ;; Your init file should contain only one such instance.
 '(c-basic-offset 4)
 '(c-comment-continuation-stars " *")
 '(c-default-style "stroustrup")
 '(c-indent-comments-syntactically-p t)
 '(c-macro-shrink-window-flag t)
 '(calendar-today-marker (quote calendar-today-face))
 '(case-fold-search t)
 '(clean-buffer-list-kill-buffer-names (quote ("*Help*" "*Apropos*" "*Man " "*Buffer List*" "*Compile-Log*" "*info*" "*vc*" "*vc-diff*" "*diff*" "*Completions*")))
 '(cperl-hairy t)
 '(cperl-indent-level 4)
 '(cperl-invalid-face (quote (quote default)))
 '(cperl-vc-header-alist (quote ((SCCS "$sccs = '%W%' ;") (RCS "$rcs = ' $Id$ ' ;") (CVS "$cvs = ' $Header$ ' ;"))))
 '(current-language-environment "English")
 '(custom-buffer-indent 4)
 '(diary-file "~/.emacs.d/.diary")
 '(display-time-24hr-format t)
 '(display-time-day-and-date t)
 '(display-time-mode t nil (time))
 '(emacs-wiki-create-backlinks t)
 '(emacs-wiki-markup-nonexistent-link t)
 '(emacs-wiki-mode-hook (quote (emacs-wiki-use-font-lock emacs-wiki-highlight-buffer footnote-mode highlight-changes-mode table-recognize emacs-wiki-use-font-lock emacs-wiki-highlight-buffer highlight-changes-mode)))
 '(ftp-program "lftp")
 '(ftp-prompt-regexp "ftp :~>")
 '(global-font-lock-mode t nil (font-lock))
 '(indent-tabs-mode nil)
 '(ispell-alternate-dictionary nil)
 '(ispell-complete-word-dict nil)
 '(kill-whole-line t)
 '(mark-diary-entries-in-calendar t)
 '(mode-line-inverse-video t)
; '(mouse-wheel-down-button 4)
; '(mouse-wheel-follow-mouse t)
; '(mouse-wheel-mode t nil (mwheel))
; '(mouse-wheel-scroll-amount (quote (5 . 20)))
; '(mouse-wheel-up-button 5)
; '(mwheel-follow-mouse t)
 '(outline-auto-activation "ask")
 '(outline-number-pages t)
 
 '(pc-select-meta-moves-sexps t)
 '(pc-select-selection-keys-only t)
 '(pc-selection-mode t nil (pc-select))

 '(ps-landscape-mode t)
 '(ps-line-number nil)
 '(ps-lpr-switches (quote ("-Zduplex")))
 '(ps-number-of-columns 2)
 '(ps-print-color-p nil)
 '(ps-printer-name "NIRM20143")
 '(ps-zebra-stripes t)

 '(quack-global-menu-p nil)
 '(quack-newline-behavior (quote indent-newline-indent))
 '(quack-pretty-lambda-p t)
 '(quack-programs (quote ("racket" "bigloo" "csi" "gosh" "gsi" "guile" "kawa" "mit-scheme" "mred -z" "mzscheme" "mzscheme -M errortrace" "rs" "scheme" "scheme48" "scsh" "sisc" "stklos" "sxi")))
 '(quack-run-scheme-always-prompts-p nil)
 '(quack-run-scheme-prompt-defaults-to-last-p nil)
 '(quack-switch-to-scheme-method (quote own-frame))

; '(tab-stop-list (quote (8 20 32 44 49 52)))
 '(today-visible-calendar-hook (quote (calendar-mark-today)))
 '(uniquify-buffer-name-style (quote forward) nil (uniquify))
 '(use-dialog-box nil)
 '(view-diary-entries-initially nil)
 '(ansi-color-names-vector ["#fdf6e3" "#dc322f" "#859900" "#b58900" "#268bd2" "#d33682" "#2aa198" "#657b83"])
 '(compilation-message-face (quote default))

 '(fci-rule-color "#eee8d5")
 '(highlight-changes-colors (quote ("#d33682" "#6c71c4")))
 '(highlight-tail-colors (quote (("#eee8d5" . 0) ("#B4C342" . 20) ("#69CABF" . 30) ("#69B7F0" . 50) ("#DEB542" . 60) ("#F2804F" . 70) ("#F771AC" . 85) ("#eee8d5" . 100))))
 '(indicate-buffer-boundaries (quote left))

 '(main-line-color1 "#222232")
 '(main-line-color2 "#333343")
 '(powerline-color1 "#222232")
 '(powerline-color2 "#333343")
 '(syslog-debug-face (quote ((t :background unspecified :foreground "#2aa198" :weight bold))))
 '(syslog-error-face (quote ((t :background unspecified :foreground "#dc322f" :weight bold))))
 '(syslog-hour-face (quote ((t :background unspecified :foreground "#859900"))))
 '(syslog-info-face (quote ((t :background unspecified :foreground "#268bd2" :weight bold))))
 '(syslog-ip-face (quote ((t :background unspecified :foreground "#b58900"))))
 '(syslog-su-face (quote ((t :background unspecified :foreground "#d33682"))))
 '(syslog-warn-face (quote ((t :background unspecified :foreground "#cb4b16" :weight bold))))
 '(vc-annotate-background nil)
 '(vc-annotate-color-map (quote ((20 . "#dc322f") (40 . "#CF4F1F") (60 . "#C26C0F") (80 . "#b58900") (100 . "#AB8C00") (120 . "#A18F00") (140 . "#989200") (160 . "#8E9500") (180 . "#859900") (200 . "#729A1E") (220 . "#609C3C") (240 . "#4E9D5B") (260 . "#3C9F79") (280 . "#2aa198") (300 . "#299BA6") (320 . "#2896B5") (340 . "#2790C3") (360 . "#268bd2"))))
 '(vc-annotate-very-old-color nil)
 '(weechat-color-list (quote (unspecified "#002b36" "#073642" "#990A1B" "#dc322f" "#546E00" "#859900" "#7B6000" "#b58900" "#00629D" "#268bd2" "#93115C" "#d33682" "#00736F" "#2aa198" "#839496" "#657b83"))))

(custom-set-faces
  ;; custom-set-faces was added by Custom -- don't edit or cut/paste it!
  ;; Your init file should contain only one such instance.
 '(calendar-today-face ((t (:box (:line-width 2 :color "grey75" :style released-button)))))
 '(mode-line ((t (:background "LightBlue" :foreground "Black" :box (:line-width 2 :color "grey75" :style released-button)))))
 '(modeline ((t (:foreground "Black" :background "LightBlue"))))
 '(widget-field-face ((t (:background "gray"))))
 '(widget-single-line-field-face ((t (:background "gray")))))

(provide 'custom-config)
